/** Declaration file generated by dts-gen */

export function destroy(component: any, removeNode: any): any;

export function destroySync(component: any, removeNode: any): void;

export function dom(tag: any, props: any, children: any): any;

export function getScheduler(): any;

export function initialize(component: any): void;

export function render(virtualNode: any, options: any): any;

export function setScheduler(customScheduler: any): void;

export function update(component: any, replaceNode: any): any;

export function updateSync(component: any, replaceNode: any): void;

export namespace dom {
    function a(props: any, children: any): any;

    function abbr(props: any, children: any): any;

    function address(props: any, children: any): any;

    function area(props: any, children: any): any;

    function article(props: any, children: any): any;

    function aside(props: any, children: any): any;

    function audio(props: any, children: any): any;

    function b(props: any, children: any): any;

    function base(props: any, children: any): any;

    function bdi(props: any, children: any): any;

    function bdo(props: any, children: any): any;

    function blockquote(props: any, children: any): any;

    function body(props: any, children: any): any;

    function br(props: any, children: any): any;

    function button(props: any, children: any): any;

    function canvas(props: any, children: any): any;

    function caption(props: any, children: any): any;

    function circle(props: any, children: any): any;

    function cite(props: any, children: any): any;

    function clipPath(props: any, children: any): any;

    function code(props: any, children: any): any;

    function col(props: any, children: any): any;

    function colgroup(props: any, children: any): any;

    function command(props: any, children: any): any;

    function datalist(props: any, children: any): any;

    function dd(props: any, children: any): any;

    function defs(props: any, children: any): any;

    function del(props: any, children: any): any;

    function details(props: any, children: any): any;

    function dfn(props: any, children: any): any;

    function dialog(props: any, children: any): any;

    function div(props: any, children: any): any;

    function dl(props: any, children: any): any;

    function dt(props: any, children: any): any;

    function ellipse(props: any, children: any): any;

    function em(props: any, children: any): any;

    function embed(props: any, children: any): any;

    function fieldset(props: any, children: any): any;

    function figcaption(props: any, children: any): any;

    function figure(props: any, children: any): any;

    function footer(props: any, children: any): any;

    function form(props: any, children: any): any;

    function g(props: any, children: any): any;

    function h1(props: any, children: any): any;

    function h2(props: any, children: any): any;

    function h3(props: any, children: any): any;

    function h4(props: any, children: any): any;

    function h5(props: any, children: any): any;

    function h6(props: any, children: any): any;

    function head(props: any, children: any): any;

    function header(props: any, children: any): any;

    function hr(props: any, children: any): any;

    function html(props: any, children: any): any;

    function i(props: any, children: any): any;

    function iframe(props: any, children: any): any;

    function image(props: any, children: any): any;

    function img(props: any, children: any): any;

    function input(props: any, children: any): any;

    function ins(props: any, children: any): any;

    function kbd(props: any, children: any): any;

    function keygen(props: any, children: any): any;

    function label(props: any, children: any): any;

    function legend(props: any, children: any): any;

    function li(props: any, children: any): any;

    function line(props: any, children: any): any;

    function linearGradient(props: any, children: any): any;

    function link(props: any, children: any): any;

    function main(props: any, children: any): any;

    function map(props: any, children: any): any;

    function mark(props: any, children: any): any;

    function mask(props: any, children: any): any;

    function menu(props: any, children: any): any;

    function meta(props: any, children: any): any;

    function meter(props: any, children: any): any;

    function nav(props: any, children: any): any;

    function noscript(props: any, children: any): any;

    function object(props: any, children: any): any;

    function ol(props: any, children: any): any;

    function optgroup(props: any, children: any): any;

    function option(props: any, children: any): any;

    function output(props: any, children: any): any;

    function p(props: any, children: any): any;

    function param(props: any, children: any): any;

    function path(props: any, children: any): any;

    function pattern(props: any, children: any): any;

    function polygon(props: any, children: any): any;

    function polyline(props: any, children: any): any;

    function pre(props: any, children: any): any;

    function progress(props: any, children: any): any;

    function q(props: any, children: any): any;

    function radialGradient(props: any, children: any): any;

    function rect(props: any, children: any): any;

    function rp(props: any, children: any): any;

    function rt(props: any, children: any): any;

    function ruby(props: any, children: any): any;

    function s(props: any, children: any): any;

    function samp(props: any, children: any): any;

    function script(props: any, children: any): any;

    function section(props: any, children: any): any;

    function select(props: any, children: any): any;

    function small(props: any, children: any): any;

    function source(props: any, children: any): any;

    function span(props: any, children: any): any;

    function stop(props: any, children: any): any;

    function strong(props: any, children: any): any;

    function style(props: any, children: any): any;

    function sub(props: any, children: any): any;

    function summary(props: any, children: any): any;

    function sup(props: any, children: any): any;

    function svg(props: any, children: any): any;

    function table(props: any, children: any): any;

    function tbody(props: any, children: any): any;

    function td(props: any, children: any): any;

    function text(props: any, children: any): any;

    function textarea(props: any, children: any): any;

    function tfoot(props: any, children: any): any;

    function th(props: any, children: any): any;

    function thead(props: any, children: any): any;

    function time(props: any, children: any): any;

    function title(props: any, children: any): any;

    function tr(props: any, children: any): any;

    function track(props: any, children: any): any;

    function tspan(props: any, children: any): any;

    function u(props: any, children: any): any;

    function ul(props: any, children: any): any;

    function video(props: any, children: any): any;

    function wbr(props: any, children: any): any;

}

